REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('28', 'Books', '<center><b>In Our Shop</b>\n\n<hr />Any book for YOU!</center>', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('24', 'for children', 'content for children. content for children. content for children. content for children.', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('18', 'Rock Music', '<center><b>Rock Music</b>\n\n<hr /><font color=\"red\">It\'s COOL Music!</font></center>', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('32', 'products banner', 'Any products.', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('35', 'test product banner', 'text', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('36', 'test url', '<center>test this <b>SHOP</b>\n\n**************</center>', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('38', 'text group banner', 'laskdf; lasd\';flk asdkljf asd\n\nf as\n\ndf \n\nas\n\nd asdfkasjdlfkajsd', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('42', 'test product banner', '', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('56', 'graph banner', '', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('57', '123', 'test description 2', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('55', 'test graphic banner for categories', 'test description', '', 'EN');
REPLACE INTO ?:aff_banner_descriptions (banner_id, title, content, alt, lang_code) VALUES ('61', 'k', 'kkk', '', 'EN');