REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('11', 'EL', 'Kατεστραμμένo κατά την άφιξη');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('12', 'EL', 'Παραγγελία λάθους προϊόντος');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('3', 'EL', 'Λαθεμένη περιγραφή αντικειμένου');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('4', 'EL', 'Δεν τίθεται σε λειτουργία');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('5', 'EL', 'Ελάττωμα κατασκευαστή');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('6', 'EL', 'Παραλαβή λάθος προϊόντος');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('7', 'EL', 'Εκτός εγγύησης');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('8', 'EL', 'Καταστροφή κατά την αποστολή');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('1', 'EL', 'Αντικατάσταση προϊόντος');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('2', 'EL', 'Αποζημίωση');
REPLACE INTO ?:rma_property_descriptions (`property_id`, `lang_code`, `property`) VALUES ('13', 'EL', 'Άλλο');